### ISSUE TITLE
make an instagram bot

### ISSUE THREAD

**Issue by neelshah2409** [neelshah2409/Bot-Collection#1]
functions require are directly upload image with caption , follow someone , like a post ,etc.

**Comment by jaiakash** [comment]
Hi, Can i work on this issue?

**Comment by neelshah2409** [comment]
> Hi, Can i work on this issue?

Yes sure, @jaiakash Go ahead!!

**Comment by jaiakash** [comment]
For follow and like some accounts, what exact account do you need to follow? like related to 
- [ ] specific hashtag or
- [ ] specific account.
