### ISSUE TITLE
[GSSOC'23] Create a Discord Poll Bot

### ISSUE THREAD

**Issue by freescetic** [neelshah2409/Bot-Collection#106]
@neelshah2409  Assign me to this task and I shall deliver my best

**Comment by freescetic** [comment]
Thanks @Shubhanshu156

**Comment by som-sama** [comment]
Hey I have already added a PR #123 

Kindly check that out. Thanks (:

**Comment by freescetic** [comment]
@Shubhanshu156 please add @som-sama as the assigned and remove me

**Comment by freescetic** [comment]
Great work @som-sama

**Comment by freescetic** [comment]
the issue is closed
