### ISSUE TITLE
Bard AI Bot ( GSSOC'23 )

### ISSUE THREAD

**Issue by Swapnil-Singh-99** [neelshah2409/Bot-Collection#141]
## Bard AI Telegram Bot

I want to create a bot that fetches the answer to a question inputted by the user and sends the answer to the user on Telegram using Bard API.

## Tech Stack

1. Python
2. Telegram Bot API
3. Bard API

I have made many telegram bots and have pretty good experience in making these.
Please assign me this issue under GSSOC'23

**Comment by Sakshiii1800** [comment]
I am a GSSOC'23 contributor Please assign this issue to me

**Comment by Swapnil-Singh-99** [comment]
Will this issue be assigned or not ?
So that I can start working on it
