### ISSUE TITLE
[GSSoC'23] Wishing bot model

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [neelshah2409/Bot-Collection#176]
Title - **Wishing Model**
Technology - **PYTHON**

**Expected behavior**
- This model will play in the terminal of PYTHON,
- This model ask the occasion of wishing,
- Play the song of that occasion in the background,
- Creating a different emojis to wish, etc.

and many more.

**Comment by Avdhesh-Varshney** [comment]
Sirs @Shubhanshu156 @neelshah2409 , please /assign this project to me to contribute under GSSoC'23.
Please sir!

**Comment by mubasharaKhan** [comment]
Assign me this issue under GSSoC'23 label

**Comment by Avdhesh-Varshney** [comment]
@Shubhanshu156 @neelshah2409 Sirs, please /assign me this task as i have done with this task and want to create pull request to contribute under GSSoC'23.

**Comment by Avdhesh-Varshney** [comment]
@shaishav06 @Shubhanshu156 @neelshah2409 Sirs, i am done with this task and want to create a pull request in this repository for successful contribution under GSSoC'23
So please assign this task for contribution

**Comment by killer2O** [comment]
@Shubhanshu156 already done in different repo https://github.com/avinashkranjan/Amazing-Python-Scripts/pull/1777
