### ISSUE TITLE
[GSSoC'23] Morse - Text Convertor

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [neelshah2409/Bot-Collection#177]
Title - **Morse to Text and Text to Morse Convertor** Project
Technology - **PYTHON**

This project will convert entered text into morse code or entered morse code into text instantly.

**Comment by Avdhesh-Varshney** [comment]
@Shubhanshu156 @neelshah2409 Sirs, Please /assign this project to me to contribute in this repository under GSSoC'23.

**Comment by Avdhesh-Varshney** [comment]
Sirs @Shubhanshu156 @neelshah2409 @shaishav06 , please /assign me this task as i have done with this task and want to create pull request to contribute under GSSoC'23.

**Comment by amankumar100** [comment]
please assign me this task  to contribute under GSSoC'23.

**Comment by ParagPatil02** [comment]
@shaishav06 @Shubhanshu156 @neelshah2409 Sirs, please /assign this issue to me to work under the program of GSSoC'23.

**Comment by amankumar100** [comment]
I have resolved this issue. Here is the link below.
https://github.com/amankumar100/Bot-Collection/tree/main/Morse%20-%20Text%20Convertor
Please explain me how will i get points for Girlscript Summer of Code 2023 in this or if you can give then please help?

**Comment by Avdhesh-Varshney** [comment]
@shaishav06 @Shubhanshu156 @neelshah2409 Sirs, please assign this task to me to contribute in this repository and for successful contribution under GSSoC'23

**Comment by killer2O** [comment]
@Shubhanshu156  already done for different repo https://github.com/avinashkranjan/Pentesting-and-Hacking-Scripts/pull/295
