### ISSUE TITLE
Support Chat Bot for the website

### ISSUE THREAD

**Issue by ayush-09** [neelshah2409/Bot-Collection#219]
The project aims to develop an AI assistance application for a website using Hugging Face's API and Pinecone's API. The application will allow users to input queries and retrieve relevant information from the website. It will provide features such as data loading to Pinecone, search functionality, and display of search results. The project will be implemented using Python and Streamlit, and it will enhance the user experience by enabling efficient and personalized information retrieval.

**Comment by ayush-09** [comment]
@neelshah2409 Please assign this task to me

**Comment by 21wh1a6625** [comment]
I would like to contribute.Can you please assign me under gssoc'23
