### ISSUE TITLE
Discord Motivation Bot

### ISSUE THREAD

**Issue by codingis4noobs2** [neelshah2409/Bot-Collection#40]
Hello @neelshah2409 , this project will give users motivational quotes on triggering '!motivate' msg.
I want to work on this issue under JWOC 🚀

**Comment by neelshah2409** [comment]
> Hello @neelshah2409 , this project will give users motivational quotes on triggering '!motivate' msg.
> 
> I want to work on this issue under JWOC 🚀

Go ahead 😊

**Comment by codingis4noobs2** [comment]
Thank you @neelshah2409 for assigning me this issue, pls label this issue as JWOC, and level of difficulty
