### ISSUE TITLE
Movie_Bot

### ISSUE THREAD

**Issue by raunakcode03** [neelshah2409/Bot-Collection#62]
Creating a movie bot for Suggesting Movies of same genre and same year by datasets of kaggle. Simple and easy bot. I want to contribute in this for GSSOC'23 @neelshah2409

**Comment by infernalsaber** [comment]
To add to this, it could be implemented as a bot which displays the details about a movie and then gives an option to give similar movies.
I would love to work together should this get approved @raunakcode03

**Comment by samarthjain422005** [comment]
i am interested in this can you please assign it to me under gssoc

**Comment by Shubhanshu156** [comment]
Assigned to @raunakcode03 you can work on this issue

**Comment by raunakcode03** [comment]
> Assigned to @raunakcode03 you can work on this issue

Thanks a lot @Shubhanshu156 🙏. GRATEFUL 😀

**Comment by infernalsaber** [comment]
@raunakcode03 would you be interested in collaborating on this?
