### ISSUE TITLE
News bot[GSSoC'23]

### ISSUE THREAD

**Issue by Somya-Singhal** [neelshah2409/Bot-Collection#76]
Hi @neelshah2409 
I want to contribute to this repo by adding a news bot that fetches and displays the latest news headlines from different sources. Users can specify their interests or categories to get news tailored to their preferences. News APIs like NewsAPI or RSS feeds can be used to fetch the news.
It would be great if I could be assigned to this issue.
Thanks

**Comment by Aditi323** [comment]
Please assign this to me as a GSSOC contributor.

**Comment by Shubhanshu156** [comment]
issue assigned to @Somya-Singhal

**Comment by Somya-Singhal** [comment]
Thanks @Shubhanshu156 . Will start working on it.
