### ISSUE TITLE
Telegram Text-To-Image Generation Bot 

### ISSUE THREAD

**Issue by Archit-Kohli** [neelshah2409/Bot-Collection#91]
### AIM ###
- A telegram bot that takes a text prompt and generates an image based on that prompt.

### DETAILS ###
- User enters a text prompt for an image.
- An image is returned using openai's dall-e API.

---

###### Please assign this issue to me ######

**Comment by akashg001** [comment]
Hi, @Archit-Kohli  I can create a text to image bot generator as i have already work on this multiple times and can easily deliver on time. uses openai and telegram bot generation earlier also.
please assign this issue me this issue under Gssoc23

**Comment by Shubhanshu156** [comment]
assigned to @Archit-Kohli
